// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantBySubdomain(ctx context.Context, subdomain string) (Tenant, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
}

var _ Querier = (*Queries)(nil)
